from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

HadesMicro = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'BMP388', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BMP388'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'BMP388:PQFN50P200X200X80-10N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'TDD01H0SB1R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TDD01H0SB1R'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'TDD01H0SB1R:SOT175P420X230-3N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'100n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'100n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'2u2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2u2'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'1u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10p', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10p'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'220n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'220n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'GR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'GR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'RE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RE'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'BL', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BL'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'D_Schottky', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Schottky'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-323', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'24CW1280T-I_OT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'24CW1280T-I_OT'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'24CW1280T-I_OT:SOT95P280X145-5N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Fuse', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Fuse'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Fuse:Fuse_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'FB_Small', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'FB_Small'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Inductor_SMD:L_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'W25N01GVZEIG_TR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'W25N01GVZEIG_TR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'W25N01GVZEIG_TR:SON127P800X600X80-9N-D', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_Molex:Molex_PicoBlade_53048-0810_1x04_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'25MHz', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'25MHz'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_Abracon_ABM8G-4Pin_3.2x2.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'74LVC1G04GX4Z', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'74LVC1G04GX4Z'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'74LVC1G04GX4Z:74AUP1G04GX4Z', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'BMI088', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BMI088'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'BMI088:PQFN50P450X300X100-16N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Jumper_NO_Small', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Jumper_NO_Small'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_1.27mm:PinHeader_1x02_P1.27mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'IIS2MDCTR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'IIS2MDCTR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'IIS2MDCTR:IIS2MDCTR', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'STM32F405RGT6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32F405RGT6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_QFP:LQFP-64_10x10mm_P0.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN),
            Pin(num='21',func=pin_types.PWRIN),
            Pin(num='22',func=pin_types.PWRIN),
            Pin(num='23',func=pin_types.PWRIN),
            Pin(num='24',func=pin_types.PWRIN),
            Pin(num='25',func=pin_types.PWRIN),
            Pin(num='26',func=pin_types.PWRIN),
            Pin(num='27',func=pin_types.PWRIN),
            Pin(num='28',func=pin_types.PWRIN),
            Pin(num='29',func=pin_types.PWRIN),
            Pin(num='30',func=pin_types.PWRIN),
            Pin(num='31',func=pin_types.PWRIN),
            Pin(num='32',func=pin_types.PWRIN),
            Pin(num='33',func=pin_types.PWRIN),
            Pin(num='34',func=pin_types.PWRIN),
            Pin(num='35',func=pin_types.PWRIN),
            Pin(num='36',func=pin_types.PWRIN),
            Pin(num='37',func=pin_types.PWRIN),
            Pin(num='38',func=pin_types.PWRIN),
            Pin(num='39',func=pin_types.PWRIN),
            Pin(num='40',func=pin_types.PWRIN),
            Pin(num='41',func=pin_types.PWRIN),
            Pin(num='42',func=pin_types.PWRIN),
            Pin(num='43',func=pin_types.PWRIN),
            Pin(num='44',func=pin_types.PWRIN),
            Pin(num='45',func=pin_types.PWRIN),
            Pin(num='46',func=pin_types.PWRIN),
            Pin(num='47',func=pin_types.PWRIN),
            Pin(num='48',func=pin_types.PWRIN),
            Pin(num='49',func=pin_types.PWRIN),
            Pin(num='50',func=pin_types.PWRIN),
            Pin(num='51',func=pin_types.PWRIN),
            Pin(num='52',func=pin_types.PWRIN),
            Pin(num='53',func=pin_types.PWRIN),
            Pin(num='54',func=pin_types.PWRIN),
            Pin(num='55',func=pin_types.PWRIN),
            Pin(num='56',func=pin_types.PWRIN),
            Pin(num='57',func=pin_types.PWRIN),
            Pin(num='58',func=pin_types.PWRIN),
            Pin(num='59',func=pin_types.PWRIN),
            Pin(num='60',func=pin_types.PWRIN),
            Pin(num='61',func=pin_types.PWRIN),
            Pin(num='62',func=pin_types.PWRIN),
            Pin(num='63',func=pin_types.PWRIN),
            Pin(num='64',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'PCA9685BS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PCA9685BS'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:QFN-28-1EP_6x6mm_P0.65mm_EP4.25x4.25mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN),
            Pin(num='21',func=pin_types.PWRIN),
            Pin(num='22',func=pin_types.PWRIN),
            Pin(num='23',func=pin_types.PWRIN),
            Pin(num='24',func=pin_types.PWRIN),
            Pin(num='25',func=pin_types.PWRIN),
            Pin(num='26',func=pin_types.PWRIN),
            Pin(num='27',func=pin_types.PWRIN),
            Pin(num='28',func=pin_types.PWRIN),
            Pin(num='29',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_02x08_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x08_Odd_Even'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_2x08_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x08', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x08'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x08_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'2k2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2k2'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'620', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'620'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'1k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'22', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'22'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'LD39200PU33R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LD39200PU33R'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LD39200PU33R:SON95P300X300X100-7N-D', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SKRPANE010', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SKRPANE010'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'SKRPANE010:SKRPADE010', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'TrmnlBlck', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TrmnlBlck'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'TerminalBlock_Phoenix:TerminalBlock_Phoenix_PT-1,5-2-3.5-H_1x02_P3.50mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_02x05_Counter_Clockwise', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x05_Counter_Clockwise'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_1.27mm:PinHeader_2x05_P1.27mm_Vertical_SMD', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'USBLC6-2SC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'otter:CH330', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'otter:CH330'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SSOP-8_3.95x5.21x3.27mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'USB_B_Micro', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_B_Micro'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_USB:USB_Micro-B_Wuerth_629105150521_CircularHoles', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='SH',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_Molex:Molex_PicoBlade_53048-0210_1x02_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] })])