from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

Hades = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'XT60-M', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'XT60-M'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'XT60-M:AMASS_XT60-M', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'100u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'100u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_Elec_6.3x7.7', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'47u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'47u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_1210_3225Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'2u2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2u2'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'100n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'100n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'4n7', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'4n7'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SD103AWS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SD103AWS'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-323', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'15u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'15u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'SRP1265A-150M:INDPM135125X650N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'G', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'G'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'0.01', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0.01'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_2512_6332Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'19k6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'19k6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'6k8', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'6k8'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'1k3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1k3'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'560', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'560'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'240', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'240'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'MIC26903YJL-TR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MIC26903YJL-TR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'MIC26903YJL-TR:MIC24054YJLTR', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN),
            Pin(num='21',func=pin_types.PWRIN),
            Pin(num='22',func=pin_types.PWRIN),
            Pin(num='23',func=pin_types.PWRIN),
            Pin(num='24',func=pin_types.PWRIN),
            Pin(num='25',func=pin_types.PWRIN),
            Pin(num='26',func=pin_types.PWRIN),
            Pin(num='27',func=pin_types.PWRIN),
            Pin(num='28',func=pin_types.PWRIN),
            Pin(num='29',func=pin_types.PWRIN),
            Pin(num='30',func=pin_types.PWRIN),
            Pin(num='31',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'LD39200PU33R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LD39200PU33R'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LD39200PU33R:SON95P300X300X100-7N-D', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'INA219AIDCNR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'INA219AIDCNR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'INA219AIDCNR:SOT65P280X145-8N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10p', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10p'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'STM32H753VITx', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32H753VITx'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_QFP:LQFP-100_14x14mm_P0.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN),
            Pin(num='21',func=pin_types.PWRIN),
            Pin(num='22',func=pin_types.PWRIN),
            Pin(num='23',func=pin_types.PWRIN),
            Pin(num='24',func=pin_types.PWRIN),
            Pin(num='25',func=pin_types.PWRIN),
            Pin(num='26',func=pin_types.PWRIN),
            Pin(num='27',func=pin_types.PWRIN),
            Pin(num='28',func=pin_types.PWRIN),
            Pin(num='29',func=pin_types.PWRIN),
            Pin(num='30',func=pin_types.PWRIN),
            Pin(num='31',func=pin_types.PWRIN),
            Pin(num='32',func=pin_types.PWRIN),
            Pin(num='33',func=pin_types.PWRIN),
            Pin(num='34',func=pin_types.PWRIN),
            Pin(num='35',func=pin_types.PWRIN),
            Pin(num='36',func=pin_types.PWRIN),
            Pin(num='37',func=pin_types.PWRIN),
            Pin(num='38',func=pin_types.PWRIN),
            Pin(num='39',func=pin_types.PWRIN),
            Pin(num='40',func=pin_types.PWRIN),
            Pin(num='41',func=pin_types.PWRIN),
            Pin(num='42',func=pin_types.PWRIN),
            Pin(num='43',func=pin_types.PWRIN),
            Pin(num='44',func=pin_types.PWRIN),
            Pin(num='45',func=pin_types.PWRIN),
            Pin(num='46',func=pin_types.PWRIN),
            Pin(num='47',func=pin_types.PWRIN),
            Pin(num='48',func=pin_types.PWRIN),
            Pin(num='49',func=pin_types.PWRIN),
            Pin(num='50',func=pin_types.PWRIN),
            Pin(num='51',func=pin_types.PWRIN),
            Pin(num='52',func=pin_types.PWRIN),
            Pin(num='53',func=pin_types.PWRIN),
            Pin(num='54',func=pin_types.PWRIN),
            Pin(num='55',func=pin_types.PWRIN),
            Pin(num='56',func=pin_types.PWRIN),
            Pin(num='57',func=pin_types.PWRIN),
            Pin(num='58',func=pin_types.PWRIN),
            Pin(num='59',func=pin_types.PWRIN),
            Pin(num='60',func=pin_types.PWRIN),
            Pin(num='61',func=pin_types.PWRIN),
            Pin(num='62',func=pin_types.PWRIN),
            Pin(num='63',func=pin_types.PWRIN),
            Pin(num='64',func=pin_types.PWRIN),
            Pin(num='65',func=pin_types.PWRIN),
            Pin(num='66',func=pin_types.PWRIN),
            Pin(num='67',func=pin_types.PWRIN),
            Pin(num='68',func=pin_types.PWRIN),
            Pin(num='69',func=pin_types.PWRIN),
            Pin(num='70',func=pin_types.PWRIN),
            Pin(num='71',func=pin_types.PWRIN),
            Pin(num='72',func=pin_types.PWRIN),
            Pin(num='73',func=pin_types.PWRIN),
            Pin(num='74',func=pin_types.PWRIN),
            Pin(num='75',func=pin_types.PWRIN),
            Pin(num='76',func=pin_types.PWRIN),
            Pin(num='77',func=pin_types.PWRIN),
            Pin(num='78',func=pin_types.PWRIN),
            Pin(num='79',func=pin_types.PWRIN),
            Pin(num='80',func=pin_types.PWRIN),
            Pin(num='81',func=pin_types.PWRIN),
            Pin(num='82',func=pin_types.PWRIN),
            Pin(num='83',func=pin_types.PWRIN),
            Pin(num='84',func=pin_types.PWRIN),
            Pin(num='85',func=pin_types.PWRIN),
            Pin(num='86',func=pin_types.PWRIN),
            Pin(num='87',func=pin_types.PWRIN),
            Pin(num='88',func=pin_types.PWRIN),
            Pin(num='89',func=pin_types.PWRIN),
            Pin(num='90',func=pin_types.PWRIN),
            Pin(num='91',func=pin_types.PWRIN),
            Pin(num='92',func=pin_types.PWRIN),
            Pin(num='93',func=pin_types.PWRIN),
            Pin(num='94',func=pin_types.PWRIN),
            Pin(num='95',func=pin_types.PWRIN),
            Pin(num='96',func=pin_types.PWRIN),
            Pin(num='97',func=pin_types.PWRIN),
            Pin(num='98',func=pin_types.PWRIN),
            Pin(num='99',func=pin_types.PWRIN),
            Pin(num='100',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'25MHz', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'25MHz'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_Abracon_ABM8G-4Pin_3.2x2.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Y', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Y'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'B'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'4k7', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'4k7'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'330', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'330'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'100', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'100'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'47', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'47'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'620', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'620'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SKRPANE010', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SKRPANE010'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'SKRPANE010:SKRPADE010', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'TDD01H0SB1R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TDD01H0SB1R'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'TDD01H0SB1R:SOT175P420X230-3N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'I2C1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'I2C1'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'TestPoint:TestPoint_Pad_D1.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'STM32F405RGTx', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32F405RGTx'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_QFP:LQFP-64_10x10mm_P0.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN),
            Pin(num='21',func=pin_types.PWRIN),
            Pin(num='22',func=pin_types.PWRIN),
            Pin(num='23',func=pin_types.PWRIN),
            Pin(num='24',func=pin_types.PWRIN),
            Pin(num='25',func=pin_types.PWRIN),
            Pin(num='26',func=pin_types.PWRIN),
            Pin(num='27',func=pin_types.PWRIN),
            Pin(num='28',func=pin_types.PWRIN),
            Pin(num='29',func=pin_types.PWRIN),
            Pin(num='30',func=pin_types.PWRIN),
            Pin(num='31',func=pin_types.PWRIN),
            Pin(num='32',func=pin_types.PWRIN),
            Pin(num='33',func=pin_types.PWRIN),
            Pin(num='34',func=pin_types.PWRIN),
            Pin(num='35',func=pin_types.PWRIN),
            Pin(num='36',func=pin_types.PWRIN),
            Pin(num='37',func=pin_types.PWRIN),
            Pin(num='38',func=pin_types.PWRIN),
            Pin(num='39',func=pin_types.PWRIN),
            Pin(num='40',func=pin_types.PWRIN),
            Pin(num='41',func=pin_types.PWRIN),
            Pin(num='42',func=pin_types.PWRIN),
            Pin(num='43',func=pin_types.PWRIN),
            Pin(num='44',func=pin_types.PWRIN),
            Pin(num='45',func=pin_types.PWRIN),
            Pin(num='46',func=pin_types.PWRIN),
            Pin(num='47',func=pin_types.PWRIN),
            Pin(num='48',func=pin_types.PWRIN),
            Pin(num='49',func=pin_types.PWRIN),
            Pin(num='50',func=pin_types.PWRIN),
            Pin(num='51',func=pin_types.PWRIN),
            Pin(num='52',func=pin_types.PWRIN),
            Pin(num='53',func=pin_types.PWRIN),
            Pin(num='54',func=pin_types.PWRIN),
            Pin(num='55',func=pin_types.PWRIN),
            Pin(num='56',func=pin_types.PWRIN),
            Pin(num='57',func=pin_types.PWRIN),
            Pin(num='58',func=pin_types.PWRIN),
            Pin(num='59',func=pin_types.PWRIN),
            Pin(num='60',func=pin_types.PWRIN),
            Pin(num='61',func=pin_types.PWRIN),
            Pin(num='62',func=pin_types.PWRIN),
            Pin(num='63',func=pin_types.PWRIN),
            Pin(num='64',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_Molex:Molex_PicoBlade_53048-0210_1x02_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SolderJumper_2_Open', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SolderJumper_2_Open'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Jumper:SolderJumper-2_P1.3mm_Open_RoundedPad1.0x1.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Jumper_3_Open', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Jumper_3_Open'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Jumper:SolderJumper-3_P1.3mm_Open_RoundedPad1.0x1.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'0', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'22', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'22'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_02x05_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x05_Odd_Even'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_1.27mm:PinHeader_2x05_P1.27mm_Vertical_SMD', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'USB_B_Micro', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_B_Micro'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_USB:USB_Micro-B_Wuerth_629105150521_CircularHoles', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='SH',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_Molex:Molex_PicoBlade_53048-0410_1x04_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_02x08_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x08_Odd_Even'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_2x08_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'2.54mm', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2.54mm'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x08_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x06', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x06'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_Molex:Molex_PicoBlade_53048-0610_1x06_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'PCA9685PW', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PCA9685PW'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:TSSOP-28_4.4x9.7mm_P0.65mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN),
            Pin(num='21',func=pin_types.PWRIN),
            Pin(num='22',func=pin_types.PWRIN),
            Pin(num='23',func=pin_types.PWRIN),
            Pin(num='24',func=pin_types.PWRIN),
            Pin(num='25',func=pin_types.PWRIN),
            Pin(num='26',func=pin_types.PWRIN),
            Pin(num='27',func=pin_types.PWRIN),
            Pin(num='28',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'24CW1280T-I_OT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'24CW1280T-I_OT'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'24CW1280T-I_OT:SOT95P280X145-5N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'W25N01GVZEIG_TR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'W25N01GVZEIG_TR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'W25N01GVZEIG_TR:SON127P800X600X80-9N-D', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'5-1814832-1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'5-1814832-1'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'5-1814832-1:TE_5-1814832-1', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'1n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'220n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'220n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'1u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'22p', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'22p'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x07', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x07'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_Molex:Molex_PicoBlade_53048-0710_1x07_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SolderJumper_3_Open', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SolderJumper_3_Open'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Jumper:SolderJumper-3_P1.3mm_Open_RoundedPad1.0x1.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'27n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'27n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Inductor_SMD:L_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'BMI088', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BMI088'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'BMI088:PQFN50P450X300X100-16N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'TMP100', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TMP100'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'MPRLS0025PA00001A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MPRLS0025PA00001A'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'MPRLS0025PA00001A:XDCR_MPRLS0025PA00001A', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'IIS2MDCTR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'IIS2MDCTR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'IIS2MDCTR:IIS2MDCTR', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'u-blox MAX-8Q', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'u-blox MAX-8Q'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'MODULE-GPS-SMD-MAX-7Q-0_18P-9.6X10MM_:GPS18P-SMD-1.1-10X9.6MM', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN)] })])