from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

HadesNT = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'10u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_1206_3216Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'100n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'100n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'33p', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'33p'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'4u7', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'4u7'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_1206_3216Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'1u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'12p', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'12p'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'2u2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2u2'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'B5819W', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'B5819W'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-123', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'GR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'GR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'RE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RE'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'YE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'YE'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'BL', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BL'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'500mA', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'500mA'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Inductor_SMD:L_1206_3216Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'100 @ 100 MHz', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'100 @ 100 MHz'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Inductor_SMD:L_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'MountingHole_Pad', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MountingHole_Pad'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'MountingHole:MountingHole_4.3mm_M4_Pad_Via', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'USB_B_Micro', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_B_Micro'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'10118193-0001LF:101181930001LF', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='SH',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_JST:JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_02x05_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x05_Odd_Even'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_1.27mm:PinHeader_2x05_P1.27mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_JST:JST_GH_SM04B-GHS-TB_1x04-1MP_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x06', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x06'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_JST:JST_GH_SM06B-GHS-TB_1x06-1MP_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x08', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x08'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_JST:JST_GH_SM08B-GHS-TB_1x08-1MP_P1.25mm_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_02x08_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x08_Odd_Even'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_2x08_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'68n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'68n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Inductor_SMD:L_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'AO3401A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AO3401A'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'MMBT3904', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MMBT3904'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'0.25', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0.25'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_1206_3216Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'120k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'120k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'39k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'39k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'100k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'100k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'DNP', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DNP'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'1k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'47', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'47'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'10k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'10k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'4k7', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'4k7'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'2k2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2k2'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'MSS3-V-T_R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MSS3-V-T_R'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'MSS3-V-T_R:MSS3VTR', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='A1',func=pin_types.PWRIN),
            Pin(num='B1',func=pin_types.PWRIN),
            Pin(num='C1',func=pin_types.PWRIN),
            Pin(num='MP1',func=pin_types.PWRIN),
            Pin(num='MP2',func=pin_types.PWRIN),
            Pin(num='MP3',func=pin_types.PWRIN),
            Pin(num='MP4',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SolderPad', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SolderPad'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'TestPoint:TestPoint_Pad_2.0x2.0mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'INA219AIDCNR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'INA219AIDCNR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-8', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'MP2451DT-LF-Z', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MP2451DT-LF-Z'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'MP2451DT-LF-Z:SOT95P280X145-6N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SRV05-4', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SRV05-4'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'W25Q128JVS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'W25Q128JVS'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-8_5.23x5.23mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'BMP280', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BMP280'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_LGA:Bosch_LGA-8_2x2.5mm_P0.65mm_ClockwisePinNumbering', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'BMX055', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BMX055'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'BMX055:LGA_PACKAGE_20_PINS', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'STM32H750VBT6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32H750VBT6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'STM32H750VBT6:QFP50P1600X1600X160-100N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN),
            Pin(num='5',func=pin_types.PWRIN),
            Pin(num='6',func=pin_types.PWRIN),
            Pin(num='7',func=pin_types.PWRIN),
            Pin(num='8',func=pin_types.PWRIN),
            Pin(num='9',func=pin_types.PWRIN),
            Pin(num='10',func=pin_types.PWRIN),
            Pin(num='11',func=pin_types.PWRIN),
            Pin(num='12',func=pin_types.PWRIN),
            Pin(num='13',func=pin_types.PWRIN),
            Pin(num='14',func=pin_types.PWRIN),
            Pin(num='15',func=pin_types.PWRIN),
            Pin(num='16',func=pin_types.PWRIN),
            Pin(num='17',func=pin_types.PWRIN),
            Pin(num='18',func=pin_types.PWRIN),
            Pin(num='19',func=pin_types.PWRIN),
            Pin(num='20',func=pin_types.PWRIN),
            Pin(num='21',func=pin_types.PWRIN),
            Pin(num='22',func=pin_types.PWRIN),
            Pin(num='23',func=pin_types.PWRIN),
            Pin(num='24',func=pin_types.PWRIN),
            Pin(num='25',func=pin_types.PWRIN),
            Pin(num='26',func=pin_types.PWRIN),
            Pin(num='27',func=pin_types.PWRIN),
            Pin(num='28',func=pin_types.PWRIN),
            Pin(num='29',func=pin_types.PWRIN),
            Pin(num='30',func=pin_types.PWRIN),
            Pin(num='31',func=pin_types.PWRIN),
            Pin(num='32',func=pin_types.PWRIN),
            Pin(num='33',func=pin_types.PWRIN),
            Pin(num='34',func=pin_types.PWRIN),
            Pin(num='35',func=pin_types.PWRIN),
            Pin(num='36',func=pin_types.PWRIN),
            Pin(num='37',func=pin_types.PWRIN),
            Pin(num='38',func=pin_types.PWRIN),
            Pin(num='39',func=pin_types.PWRIN),
            Pin(num='40',func=pin_types.PWRIN),
            Pin(num='41',func=pin_types.PWRIN),
            Pin(num='42',func=pin_types.PWRIN),
            Pin(num='43',func=pin_types.PWRIN),
            Pin(num='44',func=pin_types.PWRIN),
            Pin(num='45',func=pin_types.PWRIN),
            Pin(num='46',func=pin_types.PWRIN),
            Pin(num='47',func=pin_types.PWRIN),
            Pin(num='48',func=pin_types.PWRIN),
            Pin(num='49',func=pin_types.PWRIN),
            Pin(num='50',func=pin_types.PWRIN),
            Pin(num='51',func=pin_types.PWRIN),
            Pin(num='52',func=pin_types.PWRIN),
            Pin(num='53',func=pin_types.PWRIN),
            Pin(num='54',func=pin_types.PWRIN),
            Pin(num='55',func=pin_types.PWRIN),
            Pin(num='56',func=pin_types.PWRIN),
            Pin(num='57',func=pin_types.PWRIN),
            Pin(num='58',func=pin_types.PWRIN),
            Pin(num='59',func=pin_types.PWRIN),
            Pin(num='60',func=pin_types.PWRIN),
            Pin(num='61',func=pin_types.PWRIN),
            Pin(num='62',func=pin_types.PWRIN),
            Pin(num='63',func=pin_types.PWRIN),
            Pin(num='64',func=pin_types.PWRIN),
            Pin(num='65',func=pin_types.PWRIN),
            Pin(num='66',func=pin_types.PWRIN),
            Pin(num='67',func=pin_types.PWRIN),
            Pin(num='68',func=pin_types.PWRIN),
            Pin(num='69',func=pin_types.PWRIN),
            Pin(num='70',func=pin_types.PWRIN),
            Pin(num='71',func=pin_types.PWRIN),
            Pin(num='72',func=pin_types.PWRIN),
            Pin(num='73',func=pin_types.PWRIN),
            Pin(num='74',func=pin_types.PWRIN),
            Pin(num='75',func=pin_types.PWRIN),
            Pin(num='76',func=pin_types.PWRIN),
            Pin(num='77',func=pin_types.PWRIN),
            Pin(num='78',func=pin_types.PWRIN),
            Pin(num='79',func=pin_types.PWRIN),
            Pin(num='80',func=pin_types.PWRIN),
            Pin(num='81',func=pin_types.PWRIN),
            Pin(num='82',func=pin_types.PWRIN),
            Pin(num='83',func=pin_types.PWRIN),
            Pin(num='84',func=pin_types.PWRIN),
            Pin(num='85',func=pin_types.PWRIN),
            Pin(num='86',func=pin_types.PWRIN),
            Pin(num='87',func=pin_types.PWRIN),
            Pin(num='88',func=pin_types.PWRIN),
            Pin(num='89',func=pin_types.PWRIN),
            Pin(num='90',func=pin_types.PWRIN),
            Pin(num='91',func=pin_types.PWRIN),
            Pin(num='92',func=pin_types.PWRIN),
            Pin(num='93',func=pin_types.PWRIN),
            Pin(num='94',func=pin_types.PWRIN),
            Pin(num='95',func=pin_types.PWRIN),
            Pin(num='96',func=pin_types.PWRIN),
            Pin(num='97',func=pin_types.PWRIN),
            Pin(num='98',func=pin_types.PWRIN),
            Pin(num='99',func=pin_types.PWRIN),
            Pin(num='100',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'16 MHz', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'16 MHz'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',func=pin_types.PWRIN),
            Pin(num='2',func=pin_types.PWRIN),
            Pin(num='3',func=pin_types.PWRIN),
            Pin(num='4',func=pin_types.PWRIN)] })])